sport = ["koszykówka", "piłka", "snooker", "kręgle", "siatkówka", "hokey", "baseball", "stadion", "bieżnia", "bramka"]
matematyka = ["dodawanie", "odejmowanie", "mnożenie", "pierwiastki", "potęgi", "całki", "kwadrat", "trójkąt", "elipsa", "trapez"]
muzyka = ["wilki", "placebo", "happysad", "gitara", "fortepian", "kontrabas", "perkusja", "winyl", "mikrofon", "mikser"]
literatura = ["niewinny", "wesele", "tango", "potop", "dziady", "lalka", "kordian", "syn", "zemsta"]
filmy_seriale = ["diuna", "przyjaciele", "odlot", "tarzan", "zaplątani", "superhero", "sąsiedzi", "aladyn", "bambi", "vaiana"]